### ISSUE TITLE
aws-zone not required when passing custom upload-url

### ISSUE THREAD

**Issue by benhowell** [martinklepsch/s3-beam#44]
I'm using s3-beam for DigitalOcean spaces and therefore using custom upload-url. However, the handler checks for aws-zone and bombs out if it's not there. 

As a work-around, you can set any arbitrary aws zone (e.g. "us-east-1") as it's not used in the hash or anything.

Thanks!

**Comment by martinklepsch** [comment]
Hey @benhowell, that's a good point — would you be interested in making a PR? I'm thinking the following might be helpful for you and others:

- A note in the Readme that this also works with DO's Spaces
- Change the aws-zone assert so that it is only checked when `upload-url` url is not provided

Would be happy about your contribution 🙌

**Comment by benhowell** [comment]
Sure, I'll put it on my todo list! I'll leave the issue open until I fix it :+1:

**Comment by benhowell** [comment]
Done :-)

**Comment by benhowell** [comment]
Reopening until pulled or otherwise

**Comment by martinklepsch** [comment]
Haven’t cut a release yet but will try to do so later today. Thanks :)

**Comment by martinklepsch** [comment]
Alright I cut `0.6.0-alpha4` now — I stripped down the Digital Ocean specific documentation quite a bit, feeling that people are best of just referring to the official docs.

**Comment by benhowell** [comment]
Thanks! :+1:
